
var TROPHY_DEFS = [
  {
    id:'end_of_era',
    icon:'🏅',
    name:'End of an Era',
    name_pt:'Fim de uma Era',
    desc:'Place both The First Olympics (776 BCE) and the Last Ancient Olympics (393 CE) in one run',
    desc_pt:'Coloque as Primeiras Olimpíadas e as Últimas Olimpíadas Antigas em uma única partida',
    hint:'Place both The First Olympics (776 BCE) and the Last Ancient Olympics (393 CE) correctly in a single run — 1,169 years apart.',
    hint_pt:'Coloque as Primeiras Olimpíadas (776 a.C.) e as Últimas Olimpíadas Antigas (393 d.C.) corretamente em uma única partida — separadas por 1.169 anos.',
    trivia:'The ancient Olympics ran for 1,169 years without interruption — from 776 BCE to 393 CE, when Emperor Theodosius I banned all pagan festivals. The games were revived 1,503 years later in Athens in 1896 by Pierre de Coubertin, who had never actually seen the ancient ruins of Olympia. The marathon race was invented for the 1896 games — inspired by the legend of the soldier Pheidippides running from Marathon to Athens in 490 BCE to announce the victory over Persia, then collapsing dead. Ancient historians disagree about whether this actually happened.',
    trivia_pt:'As Olimpíadas antigas funcionaram por 1.169 anos sem interrupção — de 776 a.C. a 393 d.C., quando o Imperador Teodósio I baniu todos os festivais pagãos. Os jogos foram revividos 1.503 anos depois em Atenas em 1896 por Pierre de Coubertin, que nunca tinha visto as ruínas antigas de Olímpia. A corrida de maratona foi inventada para os jogos de 1896 — inspirada na lenda do soldado Fidípides correndo de Maratona até Atenas em 490 a.C. para anunciar a vitória sobre a Pérsia, então colapsando morto.',
    needed:['The First Olympics','Last Ancient Olympics']
  },
  {
    id:'pax_romana',
    icon:'🏛️',
    name:'Pax Romana',
    name_pt:'Pax Romana',
    desc:'Place Founding of Rome, Roman Republic, Roman Empire & Fall of the Western Roman Empire correctly in one run',
    desc_pt:'Coloque a Fundação de Roma, a República Romana, o Império Romano e a Queda do Império Romano do Ocidente em uma partida',
    hint:'Place Founding of Rome, Roman Republic, Roman Empire, and Fall of the Western Roman Empire correctly in a single run.',
    hint_pt:'Coloque a Fundação de Roma, a República Romana, o Império Romano e a Queda do Império Romano do Ocidente corretamente em uma partida.',
    trivia:'The Western Roman Empire officially "fell" in 476 CE when the Germanic chieftain Odoacer deposed Romulus Augustulus — but this was barely noticed at the time. The Eastern Roman Empire (Byzantine) continued for another 977 years until 1453 CE. Historians now debate whether Rome ever truly "fell" or simply transformed: its laws, language (Latin evolved into French, Spanish, Italian, Romanian, Portuguese), calendar, Catholic Church structure, and architectural vocabulary shaped Western civilization so deeply that in a sense, Rome never ended.',
    trivia_pt:'O Império Romano Ocidental oficialmente "caiu" em 476 d.C. quando o chefe germânico Odoacro depôs Rômulo Augústulo — mas isso mal foi notado na época. O Império Romano Oriental (Bizâncio) continuou por mais 977 anos até 1453 d.C. Os historiadores agora debatem se Roma realmente "caiu" ou simplesmente se transformou: suas leis, língua (o latim evoluiu para o francês, espanhol, italiano, romeno, português), calendário, estrutura da Igreja Católica e vocabulário arquitetônico moldaram tão profundamente a civilização ocidental que, em certo sentido, Roma nunca terminou.',
    needed:['Founding of Rome','Roman Republic','Roman Empire','Fall of the Western Roman Empire']
  },
  {
    id:'julio_claudian',
    icon:'⚔️',
    name:'Julio-Claudian Dynasty',
    name_pt:'Dinastia Júlio-Cláudia',
    desc:'Caesar would be proud — place Augustus, Tiberius, Caligula, Claudius & Nero in one run',
    desc_pt:'César ficaria orgulhoso — coloque Augusto, Tibério, Calígula, Cláudio e Nero em uma partida',
    hint:'Place all 5 Julio-Claudian emperors in a single run: Augustus · Tiberius · Caligula · Claudius · Nero',
    hint_pt:'Coloque os 5 imperadores Júlio-Claudianos em uma partida: Augusto · Tibério · Calígula · Cláudio · Nero',
    trivia:'The Julio-Claudian dynasty produced Rome\'s first five emperors (27 BCE–68 CE), and almost all of them died violently or in disgrace. Augustus died naturally (possibly poisoned by his wife Livia). Tiberius was smothered. Caligula was stabbed 30 times. Claudius was poisoned with mushrooms. Nero fled Rome, declared an enemy of the state, and killed himself at 30 — reportedly saying "What an artist the world loses in me." The dynasty ended not with a bang but with a whimper.',
    trivia_pt:'A dinastia Júlio-Cláudia produziu os primeiros cinco imperadores de Roma (27 a.C.–68 d.C.), e quase todos morreram violentamente ou em desgraça. Augusto morreu naturalmente (possivelmente envenenado por sua esposa Lívia). Tibério foi sufocado. Calígula foi esfaqueado 30 vezes. Cláudio foi envenenado com cogumelos. Nero fugiu de Roma, declarado inimigo do estado, e se matou aos 30 anos — supostamente dizendo "Que artista o mundo perde em mim."',
    needed:['Augustus','Tiberius','Caligula','Claudius','Nero']
  },
  {
    id:'flavian',
    icon:'🦅',
    name:'Flavian Dynasty',
    name_pt:'Dinastia Flaviana',
    desc:'Place Vespasian, Titus & Domitian correctly in a single run — the three Flavian Emperors',
    desc_pt:'Coloque Vespasiano, Tito e Domiciano corretamente em uma partida — os três Imperadores Flávios',
    hint:'Place Vespasian, Titus, and Domitian correctly in a single run. All three were emperors of the Flavian dynasty (69–96 CE).',
    hint_pt:'Coloque Vespasiano, Tito e Domiciano corretamente em uma partida. Os três foram imperadores da dinastia flaviana (69–96 d.C.).',
    trivia:'The Flavian dynasty (69–96 CE) rose from the chaos of the Year of the Four Emperors. Vespasian, a general fighting in Judea, marched on Rome and restored order. His reign funded the construction of the Colosseum, paid for with the spoils of Jerusalem. His son Titus completed it — then suffered one of history\'s cruellest ironies: his reign saw Vesuvius bury Pompeii (79 CE), a massive plague, and a great fire in Rome. Domitian, the last Flavian, was remembered as a tyrant by senators but loved by the army. His assassination in 96 CE ended the dynasty.',
    trivia_pt:'A dinastia flaviana (69–96 d.C.) surgiu do caos do Ano dos Quatro Imperadores. Vespasiano, general lutando na Judeia, marchou sobre Roma e restaurou a ordem. Seu reinado financiou a construção do Coliseu, pago com os espólios de Jerusalém. Seu filho Tito o completou — mas sofreu uma das ironias mais cruéis da história: seu reinado viu o Vesúvio sepultar Pompeia (79 d.C.), uma grande peste e um grande incêndio em Roma. Domiciano, o último flaviano, foi lembrado como tirano pelos senadores, mas amado pelo exército.',
    needed:['Vespasian','Titus','Domitian']
  },
  {
    id:'five_good',
    icon:'⭐',
    name:'Five Good Emperors',
    name_pt:'Cinco Bons Imperadores',
    desc:'Place Nerva, Trajan, Hadrian, Antoninus Pius & Marcus Aurelius correctly in one run',
    desc_pt:'Coloque Nerva, Trajano, Adriano, Antonino Pio e Marco Aurélio corretamente em uma partida',
    hint:'Place all 5 Good Emperors correctly in a single run: Nerva · Trajan · Hadrian · Antoninus Pius · Marcus Aurelius',
    hint_pt:'Coloque os 5 Bons Imperadores corretamente em uma partida: Nerva · Trajano · Adriano · Antonino Pio · Marco Aurélio',
    trivia:'The Five Good Emperors (96–180 CE) were named by historian Edward Gibbon, who called their era "the period in the history of the world during which the condition of the human race was most happy." All five ruled wisely and chose their successors by merit rather than birth — until Marcus Aurelius broke the pattern by choosing his biological son Commodus, who turned out to be a catastrophically bad emperor who liked to fight in the Colosseum dressed as Hercules.',
    trivia_pt:'Os Cinco Bons Imperadores (96–180 d.C.) foram nomeados pelo historiador Edward Gibbon, que chamou sua era de "o período da história do mundo durante o qual a condição da raça humana foi mais feliz." Todos os cinco governaram sabiamente e escolheram seus sucessores pelo mérito — até Marco Aurélio quebrar o padrão ao escolher seu filho biológico Cômodo, que se revelou um imperador catastroficamente ruim que gostava de lutar no Coliseu vestido de Hércules.',
    needed:['Nerva','Trajan','Hadrian','Antoninus Pius','Marcus Aurelius']
  },
  {
    id:'king_of_kings',
    icon:'👑',
    name:'King of Kings',
    name_pt:'Rei dos Reis',
    desc:'Place all Classical Roman & Byzantine Emperors correctly in a single run',
    desc_pt:'Coloque todos os Imperadores Romanos e Bizantinos Clássicos corretamente em uma única partida',
    hint:'Place all 17 Roman and Byzantine emperors in a single run: Augustus through Justinian I.',
    hint_pt:'Coloque todos os 17 imperadores romanos e bizantinos em uma partida: de Augusto a Justiniano I.',
    trivia:'The Roman emperorship spanned five centuries and dozens of rulers — yet remarkably, only one Roman emperor ever voluntarily resigned: Diocletian, in 305 CE, who then retired to grow cabbages in Split, Croatia. When factions pressured him to return to power, he reportedly replied: "If you could show the cabbage that I planted with my own hands to your emperor, he definitely wouldn\'t dare suggest that I replace the peace and happiness of this place with the storms of a never-satisfied greed." The palace he built in retirement became the old city of Split.',
    trivia_pt:'O império romano abrangeu cinco séculos e dezenas de governantes — mas, notavelmente, apenas um imperador romano renunciou voluntariamente: Diocleciano, em 305 d.C., que se aposentou para cultivar couves em Split, na Croácia. Quando facções o pressionaram a voltar ao poder, ele teria respondido: "Se você pudesse mostrar ao seu imperador a couve que plantei com minhas próprias mãos, ele certamente não ousaria sugerir que eu trocasse a paz e a felicidade deste lugar pelas tempestades de uma ganância jamais satisfeita."',
    needed:['Augustus', 'Tiberius', 'Caligula', 'Claudius', 'Nero', 'Vespasian', 'Titus', 'Domitian', 'Nerva', 'Trajan', 'Hadrian', 'Antoninus Pius', 'Marcus Aurelius', 'Diocletian', 'Constantine the Great', 'Theodosius I', 'Justinian I']
  },
  {
    id:'crusader',
    icon:'✝️',
    name:'Crusader',
    name_pt:'Cruzado',
    desc:'Place all nine Crusades correctly in a single run',
    desc_pt:'Coloque todas as nove Cruzadas corretamente em uma única partida',
    hint:'Place all nine Crusades (First through Ninth) in one run.',
    hint_pt:'Coloque todas as nove Cruzadas (Primeira à Nona) em uma partida.',
    trivia:'The Crusades (1095–1291) began in 1095 when Pope Urban II called for a holy war at the Council of Clermont. Participants were promised the remission of sins for fighting. The First Crusade (1096–1099) succeeded and captured Jerusalem in 1099, but later crusades struggled with logistics, politics, and rivalries. The Fourth Crusade (1202–1204) famously never reached the Holy Land and instead sacked Constantinople in 1204, a Christian city.',
    trivia_pt:'As Cruzadas (1095–1291) começaram em 1095 quando o Papa Urbano II convocou uma guerra santa no Concílio de Clermont. Os participantes receberam a promessa de remissão dos pecados por lutar. A Primeira Cruzada (1096–1099) teve sucesso e conquistou Jerusalém em 1099, mas as cruzadas posteriores enfrentaram dificuldades logísticas, políticas e rivalidades. A Quarta Cruzada (1202–1204) ficou famosa por nunca chegar à Terra Santa e terminar saqueando Constantinopla em 1204, uma cidade cristã.',
    needed:['First Crusade','Second Crusade','Third Crusade','Fourth Crusade','Fifth Crusade','Sixth Crusade','Seventh Crusade','Eighth Crusade','Ninth Crusade']
  },
  {
    id:'silk_trader',
    icon:'🧵',
    name:'Silk Trader',
    name_pt:'Mercador de Seda',
    desc:'Place the Silk Road, Great Wall of China & Pharaonic Egypt correctly in a single run',
    desc_pt:'Coloque a Rota da Seda, a Grande Muralha da China e o Egito Faraônico corretamente em uma partida',
    hint:'Place the Silk Road, Great Wall of China, and Pharaonic Egypt correctly in a single run.',
    hint_pt:'Coloque a Rota da Seda, a Grande Muralha da China e o Egito Faraônico corretamente em uma partida.',
    trivia:'The Silk Road and the Great Wall of China were deeply intertwined: the Wall was built partly to protect the trade routes, while the trade routes funded the empire that built the Wall. Chinese silk was so prized in Rome that Roman senators tried to ban it — not because of the cost, but because they considered silk clothing scandalously transparent and immodest. The Roman elite wore it anyway. Rome\'s trade deficit with China was so severe that Pliny the Elder complained it was draining the empire\'s gold reserves.',
    trivia_pt:'A Rota da Seda e a Grande Muralha da China estavam profundamente interligadas: a Muralha foi construída em parte para proteger as rotas comerciais, enquanto as rotas comerciais financiavam o império que construiu a Muralha. A seda chinesa era tão valorizada em Roma que os senadores romanos tentaram bani-la — não por causa do custo, mas porque consideravam as roupas de seda escandalosamente transparentes. O déficit comercial de Roma com a China era tão severo que Plínio, o Velho, reclamou que estava drenando as reservas de ouro do império.',
    needed:['Silk Road','Great Wall of China','Pharaonic Egypt']
  },
  {
    id:'renaissancist',
    icon:'🎨',
    name:'Renaissancist',
    name_pt:'Renascentista',
    desc:'Place Leonardo da Vinci, Michelangelo, Galileo, Shakespeare & the Renaissance era in one run',
    desc_pt:'Coloque Leonardo da Vinci, Michelangelo, Galileu, Shakespeare e a era Renascentista em uma partida',
    hint:'Place Leonardo da Vinci, Michelangelo, Galileo Galilei, William Shakespeare, and the Renaissance era card correctly in one run.',
    hint_pt:'Coloque Leonardo da Vinci, Michelangelo, Galileu Galilei, William Shakespeare e a carta da era Renascentista corretamente em uma partida.',
    trivia:'Leonardo da Vinci and Michelangelo actually knew each other in Florence and reportedly did not get along — they were rivals with sharply contrasting personalities. Leonardo was elegant, curious, perpetually unfinished, left-handed, and vegetarian. Michelangelo was famously filthy (reportedly didn\'t bathe for months), aggressive, and obsessively devoted to completion. When Michelangelo publicly mocked Leonardo for abandoning the bronze horse commission, Leonardo reportedly looked away without responding.',
    trivia_pt:'Leonardo da Vinci e Michelangelo se conheceram em Florença e aparentemente não se davam bem — eram rivais com personalidades marcadamente diferentes. Leonardo era elegante, curioso, perpetuamente inacabado, canhoto e vegetariano. Michelangelo era notoriamente sujo (supostamente não tomava banho por meses), agressivo e obsessivamente dedicado à conclusão. Quando Michelangelo zombou publicamente de Leonardo por abandonar a encomenda do cavalo de bronze, Leonardo supostamente desviou o olhar sem responder.',
    needed:['Leonardo da Vinci','Michelangelo','Galileo Galilei','William Shakespeare','Renaissance']
  },
  {
    id:'scientist',
    icon:'🔬',
    name:'Man of Science',
    name_pt:'Homem da Ciencia',
    desc:'Place Archimedes, Nicolaus Copernicus, Galileo Galilei, Isaac Newton & Charles Darwin in one run',
    desc_pt:'Coloque Arquimedes, Nicolau Copérnico, Galileu Galilei, Isaac Newton e Charles Darwin em uma partida',
    hint:'Place Archimedes, Nicolaus Copernicus, Galileo Galilei, Isaac Newton, and Charles Darwin correctly in a single run.',
    hint_pt:'Coloque Arquimedes, Nicolau Copérnico, Galileu Galilei, Isaac Newton e Charles Darwin corretamente em uma partida.',
    trivia:'Isaac Newton reportedly said he could see further "by standing on the shoulders of giants" — referring to Descartes, Galileo, and Kepler before him. Newton himself was remarkably petty about sharing credit: his feud with Leibniz over who invented calculus was so bitter that British mathematicians refused to use the superior Leibniz notation for over a century, holding British mathematics back. Newton also spent more time on alchemy and biblical prophecy than on physics — his alchemical manuscripts fill two million words.',
    trivia_pt:'Isaac Newton supostamente disse que podia ver mais longe "ao ficar nos ombros de gigantes" — referindo-se a Descartes, Galileu e Kepler antes dele. Newton mesmo era notavelmente mesquinho quanto a compartilhar crédito: sua disputa com Leibniz sobre quem inventou o cálculo foi tão amarga que os matemáticos britânicos se recusaram a usar a notação superior de Leibniz por mais de um século. Newton também passou mais tempo em alquimia e profecia bíblica do que em física — seus manuscritos alquímicos preenchem dois milhões de palavras.',
    needed:['Archimedes','Nicolaus Copernicus','Galileo Galilei','Isaac Newton','Charles Darwin']
  },
  {
    id:'warlord',
    icon:'🗡️',
    name:'Warlord',
    name_pt:'Senhor da Guerra',
    desc:'Place 8 or more war cards correctly in a single run',
    desc_pt:'Coloque 8 ou mais cartas de guerra corretamente em uma partida',
    hint:'Place at least 8 war-related cards in one run. Counted: WWI, WWII, Korean War, Vietnam War, Hundred Years War, Thirty Years War, Persian Wars, Punic Wars, American Civil War, American Revolution, French Revolution, Trojan War, Cold War.',
    hint_pt:'Coloque pelo menos 8 cartas relacionadas à guerra em uma partida. Contadas: IGM, IIGM, Guerra da Coreia, Guerra do Vietnã, Guerra dos Cem Anos, Guerra dos Trinta Anos, Guerras Persas, Guerras Púnicas, Guerra Civil Americana, Revolução Americana, Revolução Francesa, Guerra de Tróia, Guerra Fria.',
    trivia:'The 20th century was by far the deadliest in human history: WWI killed ~20 million, WWII killed 70–85 million (including the Holocaust\'s 6 million Jews and millions of others), and the Cold War proxy conflicts — Korea, Vietnam, and dozens of others — killed tens of millions more. Despite this, the post-1945 era has seen the longest period without direct war between great powers in modern history, a trend called the "Long Peace" by Steven Pinker.',
    trivia_pt:'O século XX foi de longe o mais mortífero da história humana: a IGM matou ~20 milhões, a IIGM matou 70–85 milhões (incluindo os 6 milhões de judeus do Holocausto), e os conflitos proxy da Guerra Fria mataram dezenas de milhões a mais. Apesar disso, a era pós-1945 viu o período mais longo sem guerra direta entre grandes potências na história moderna, uma tendência chamada de "Longa Paz" por Steven Pinker.',
    needed:null,
    special:'warlord'
  },
  {
    id:'revolution',
    icon:'✊',
    name:'Age of Revolutions',
    name_pt:'Era das Revoluções',
    desc:'Place American Revolution, French Revolution, Russian Revolution & Haitian Revolution in one run',
    desc_pt:'Coloque a Revolução Americana, Francesa, Russa e Haitiana em uma partida',
    hint:'Place American Revolution, French Revolution, Russian Revolution, and Haitian Revolution correctly in a single run.',
    hint_pt:'Coloque a Revolução Americana, a Revolução Francesa, a Revolução Russa e a Revolução Haitiana corretamente em uma partida.',
    trivia:'The four great revolutions of the modern era were directly connected: the American Revolution (1776) inspired the French Revolution (1789), whose Declaration of the Rights of Man inspired the Haitian revolutionaries in Saint-Domingue. The French Revolution in turn inspired Marx and Engels, whose Communist Manifesto (1848) became the intellectual blueprint for the Russian Revolution (1917). Napoleon\'s chaos after the French Revolution also weakened European colonial power — helping Latin American independence movements succeed in the 1810s–1820s.',
    trivia_pt:'As quatro grandes revoluções da era moderna estavam diretamente conectadas: a Revolução Americana (1776) inspirou a Revolução Francesa (1789), cuja Declaração dos Direitos do Homem inspirou os revolucionários haitianos. A Revolução Francesa por sua vez inspirou Marx e Engels, cujo Manifesto Comunista (1848) tornou-se o projeto intelectual da Revolução Russa (1917). O caos de Napoleão após a Revolução Francesa também enfraqueceu o poder colonial europeu — ajudando os movimentos de independência da América Latina.',
    needed:['American Revolution','French Revolution','Russian Revolution','Haitian Revolution']
  },
  {
    id:'world_war',
    icon:'💣',
    name:'The Great Wars',
    name_pt:'As Grandes Guerras',
    desc:'Place World War I, World War II & the Atomic Bombing of Hiroshima & Nagasaki in one run',
    desc_pt:'Coloque a Primeira Guerra Mundial, a Segunda Guerra Mundial e o Bombardeio de Hiroshima e Nagasaki em uma partida',
    hint:'Place World War I, World War II, and Atomic Bombing of Hiroshima & Nagasaki correctly in a single run.',
    hint_pt:'Coloque a Primeira Guerra Mundial, a Segunda Guerra Mundial e o Bombardeio Atômico de Hiroshima e Nagasaki corretamente em uma partida.',
    trivia:'When the atomic bomb was tested at Trinity on July 16, 1945, J. Robert Oppenheimer famously quoted the Bhagavad Gita: "Now I am become Death, the destroyer of worlds." Less famous is what his brother Frank said at the same moment: "It worked." Less famous still is what General Kenneth Bainbridge, the test director, said to Oppenheimer immediately after: "Now we are all sons of bitches." Oppenheimer reportedly agreed this was the most accurate thing said that day.',
    trivia_pt:'Quando a bomba atômica foi testada em Trinity em 16 de julho de 1945, J. Robert Oppenheimer famosamente citou o Bhagavad Gita: "Agora me tornei a Morte, o destruidor de mundos." Menos famoso é o que seu irmão Frank disse no mesmo momento: "Funcionou." Menos famoso ainda é o que o General Kenneth Bainbridge, diretor do teste, disse a Oppenheimer imediatamente depois: "Agora somos todos filhos da puta." Oppenheimer supostamente concordou que isso foi a coisa mais precisa dita naquele dia.',
    needed:['World War I','World War II','Atomic Bombing of Hiroshima & Nagasaki']
  },
  {
    id:'cold_warrior',
    icon:'☢️',
    name:'Cold Warrior',
    name_pt:'Guerreiro Frio',
    desc:'Place Cold War, Cuban Missile Crisis, Korean War & Vietnam War correctly in one run',
    desc_pt:'Coloque a Guerra Fria, a Crise dos Mísseis de Cuba, a Guerra da Coreia e a Guerra do Vietnã em uma partida',
    hint:'Place Cold War, Cuban Missile Crisis, Korean War, and Vietnam War correctly in a single run.',
    hint_pt:'Coloque a Guerra Fria, a Crise dos Mísseis de Cuba, a Guerra da Coreia e a Guerra do Vietnã corretamente em uma partida.',
    trivia:'The Cuban Missile Crisis came within a single decision of nuclear war. On October 27, 1962, a Soviet submarine (B-59) was depth-charged by US warships who did not know it was nuclear-armed. Inside the submarine, communications were cut, the crew believed war had begun, and two of the three officers required to authorize a nuclear torpedo launch gave their approval. The third — Vasili Arkhipov — refused. His single dissenting vote prevented a nuclear strike that would almost certainly have triggered full nuclear war between the superpowers.',
    trivia_pt:'A Crise dos Mísseis de Cuba chegou a uma única decisão da guerra nuclear. Em 27 de outubro de 1962, um submarino soviético (B-59) foi bombardeado com cargas de profundidade por navios de guerra americanos que não sabiam que estava armado com armas nucleares. Dentro do submarino, dois dos três oficiais necessários para autorizar um torpedo nuclear aprovaram o lançamento. O terceiro — Vasili Arkhipov — recusou. Seu único voto contrário impediu um ataque nuclear que quase certamente teria desencadeado uma guerra nuclear total.',
    needed:['Cold War','Cuban Missile Crisis','Korean War','Vietnam War']
  },
  {
    id:'vienna',
    icon:'🎭',
    name:'Vienna Crossover',
    name_pt:'Cruzamento de Viena',
    desc:'Place Hitler, Freud & Stalin in one run — all once lived in Vienna simultaneously',
    desc_pt:'Coloque Hitler, Freud e Stalin em uma partida — todos viveram em Viena simultaneamente',
    hint:'Place Adolf Hitler, Sigmund Freud & Joseph Stalin correctly in a single run. All three actually lived in Vienna at the same time, between 1908–1913.',
    hint_pt:'Coloque Adolf Hitler, Sigmund Freud e Joseph Stalin corretamente em uma partida. Os três realmente viveram em Viena ao mesmo tempo, entre 1908–1913.',
    trivia:'Between 1908 and 1913, Vienna hosted one of history\'s most extraordinary coincidences: Adolf Hitler (a failed art student, 19–24), Sigmund Freud (at the height of his psychoanalytic career, 52–57), Joseph Stalin (briefly, attending a conference), and Leon Trotsky (living in exile, writing for a chess column in a Viennese café) all lived in the same city simultaneously. None of them knew each other. Archduke Franz Ferdinand also lived there — whose 1914 assassination would trigger WWI.',
    trivia_pt:'Entre 1908 e 1913, Viena abrigou uma das coincidências mais extraordinárias da história: Adolf Hitler (um estudante de arte fracassado, 19–24 anos), Sigmund Freud (no auge de sua carreira psicanalítica, 52–57 anos), Joseph Stalin (brevemente, para uma conferência) e Leon Trotsky (vivendo no exílio, escrevendo para uma coluna de xadrez em um café vienense) todos viveram na mesma cidade simultaneamente. Nenhum deles se conhecia.',
    needed:['Adolf Hitler','Sigmund Freud','Joseph Stalin']
  },
  {
    id:'rocket_man',
    icon:'🚀',
    name:'Rocket Man',
    name_pt:'Homem Foguete',
    desc:'Place all space-race cards correctly in a single run',
    desc_pt:'Coloque todas as cartas da corrida espacial corretamente em uma partida',
    hint:'Place First Man in Space (1961), Moon Landing (1969) & Space Age (1957–) correctly in one run.',
    hint_pt:'Coloque Primeiro Homem no Espaço (1961), Pouso na Lua (1969) e Era Espacial (1957–) corretamente em uma partida.',
    trivia:'The Space Race lasted only 12 years from Sputnik (1957) to the Moon Landing (1969), yet produced technology that now underpins modern life: GPS, weather satellites, memory foam, water filtration, and scratch-resistant lenses. The Apollo program cost $280 billion in today\'s money. Neil Armstrong\'s famous line "one small step for man, one giant leap for mankind" was supposed to include the word "a" — "one small step for a man" — but it was lost in transmission. Armstrong maintained for the rest of his life that he did say "a man."',
    trivia_pt:'A Corrida Espacial durou apenas 12 anos do Sputnik (1957) ao Pouso na Lua (1969), mas produziu tecnologia que agora sustenta a vida moderna: GPS, satélites meteorológicos, espuma de memória, filtração de água e lentes resistentes a arranhões. O programa Apollo custou 280 bilhões de dólares em valores atuais. A famosa frase de Neil Armstrong "um pequeno passo para o homem, um salto gigante para a humanidade" deveria incluir a palavra "um" — "um pequeno passo para um homem" — mas foi perdida na transmissão.',
    needed:['First Man in Space','Moon Landing','Space Age']
  },
  {
    id:'empire_builder',
    icon:'🌍',
    name:'Empire Builder',
    name_pt:'Construtor de Impérios',
    desc:'Place 10 or more interval (empire/era) cards correctly in a single run',
    desc_pt:'Coloque 10 ou mais cartas de intervalos (impérios/eras) corretamente em uma única partida',
    hint:'Place at least 10 empire/era range cards correctly in one run. Try Empires mode for the best chance!',
    hint_pt:'Coloque pelo menos 10 cartas de impérios/eras corretamente em uma partida. Tente o modo Impérios para a melhor chance!',
    trivia:'At its peak, the British Empire controlled roughly 24% of the Earth\'s land surface and 23% of its population — making it the largest empire in history by land area. The Roman Empire at its peak controlled about 5 million km² and 21% of the world\'s population. The Mongol Empire under Genghis Khan and his successors controlled the largest contiguous land empire ever — 24 million km² — but the British Empire was larger when its maritime territories are included. The sun literally never set on it: at any moment of the day, some part of the British Empire was in daylight.',
    trivia_pt:'Em seu auge, o Império Britânico controlava aproximadamente 24% da superfície terrestre da Terra e 23% de sua população — tornando-o o maior império da história em área terrestre. O Império Romano em seu auge controlava cerca de 5 milhões de km² e 21% da população mundial. O Império Mongol sob Gengis Khan e seus sucessores controlava o maior império terrestre contíguo — 24 milhões de km² — mas o Império Britânico era maior quando seus territórios marítimos são incluídos.',
    needed:null,
    special:'ten_intervals'
  },
  {
    id:'centurion',
    icon:'🛡️',
    name:'Centurion',
    name_pt:'Centurião',
    desc:'Place 100 cards correctly in a single run',
    desc_pt:'Coloque 100 cartas corretamente em uma única partida',
    hint:'Place 100 cards correctly in a single run. Try Classic mode with All Ages and Free Play (no lives) for maximum cards.',
    hint_pt:'Coloque 100 cartas corretamente em uma única partida. Tente o modo Clássico com Todas as Eras e Jogo Livre (sem vidas) para o máximo de cartas.',
    trivia:'A Roman centurion commanded a "century" — theoretically 100 soldiers, in practice usually 80. Centurions were the backbone of the Roman army: professional, experienced soldiers who rose through the ranks. They carried a vine staff (vitis) as their symbol of authority and were known for being brutal disciplinarians. The most senior centurion of a legion, the Primus Pilus ("First Spear"), was one of the most respected positions in the entire Roman military.',
    trivia_pt:'Um centurião romano comandava uma "centúria" — teoricamente 100 soldados, na prática geralmente 80. Os centuriões eram a espinha dorsal do exército romano: soldados profissionais e experientes que ascendiam pelas fileiras. Eles carregavam um bastão de vinha (vitis) como símbolo de autoridade. O centurião mais sênior de uma legião, o Primus Pilus ("Primeira Lança"), era uma das posições mais respeitadas em todo o exército romano.',
    needed:null,
    special:'hundred_cards'
  },
  {
    id:'librarian',
    icon:'📚',
    name:'Librarian of Alexandria',
    name_pt:'Bibliotecário de Alexandria',
    desc:'Discover every single card in the Compendium',
    desc_pt:'Descubra todas as cartas do Compêndio',
    hint:'Keep playing across all game modes until you have encountered every card at least once. Cards are added to the Compendium when you see or place them in a game.',
    hint_pt:'Continue jogando em todos os modos até encontrar todas as cartas pelo menos uma vez. As cartas são adicionadas ao Compêndio quando você as vê ou coloca em um jogo.',
    trivia:'The Library of Alexandria, founded around 300 BCE under Ptolemy I, is estimated to have held 400,000–700,000 scrolls — the largest collection of knowledge in the ancient world. It was not burned in a single dramatic fire (a popular myth), but gradually declined through funding cuts and political neglect over centuries. Julius Caesar accidentally burned some scrolls during the siege of 48 BCE. It likely ceased to function as a major institution around the 3rd century CE. A new Bibliotheca Alexandrina opened in Egypt in 2002.',
    trivia_pt:'A Biblioteca de Alexandria, fundada por volta de 300 a.C. sob Ptolomeu I, estima-se ter guardado 400.000–700.000 pergaminhos — a maior coleção de conhecimento do mundo antigo. Ela não foi queimada em um único incêndio dramático (um mito popular), mas gradualmente declinou ao longo de séculos. O Júlio César acidentalmente queimou alguns pergaminhos durante o cerco de 48 a.C. Uma nova Bibliotheca Alexandrina foi inaugurada no Egito em 2002.',
    needed:null,
    special:'compendium_complete'
  },
  {
    id:'iron_mind',
    icon:'🧠',
    name:'Iron Mind',
    name_pt:'Mente de Ferro',
    desc:'Score 500 points or more in a single run',
    desc_pt:'Pontue 500 pontos ou mais em uma única partida',
    hint:'Accumulate 500+ points in one run. Build long streaks (bonus points per card × streak multiplier) and place empire cards (worth up to 30 points each).',
    hint_pt:'Acumule 500+ pontos em uma partida. Construa longas sequências (pontos bônus por carta × multiplicador de sequência) e coloque cartas de impérios (valendo até 30 pontos cada).',
    trivia:'The human brain\'s ability to store and retrieve historical information is far stranger than it seems. The "spacing effect" — discovered by Hermann Ebbinghaus in 1885 — shows that memories decay exponentially after learning but can be made permanent with spaced repetition. Ebbinghaus memorized thousands of nonsense syllables to chart his own forgetting curve. Modern spaced repetition software (like Anki) uses his mathematics to optimize when to review each fact. Reviewing at the right moment can make a memory last a lifetime from just a few exposures.',
    trivia_pt:'A capacidade do cérebro humano de armazenar e recuperar informações históricas é muito mais estranha do que parece. O "efeito de espaçamento" — descoberto por Hermann Ebbinghaus em 1885 — mostra que as memórias decaem exponencialmente após o aprendizado, mas podem ser tornadas permanentes com repetição espaçada. O software moderno de repetição espaçada (como o Anki) usa sua matemática para otimizar quando revisar cada fato.',
    needed:null,
    special:'score_500'
  },
  {
    id:'on_fire',
    icon:'🔥',
    name:'On Fire',
    name_pt:'Em Chamas',
    desc:'Reach a streak of 50 or more in a single run',
    desc_pt:'Alcance uma sequência de 50 ou mais em uma única partida',
    hint:'Place 50 cards correctly in a row without a single mistake. Try Free Play mode (no lives) so mistakes don\'t end the game.',
    hint_pt:'Coloque 50 cartas corretamente em sequência sem um único erro. Tente o modo Jogo Livre (sem vidas) para que os erros não encerrem o jogo.',
    trivia:'The psychological phenomenon of being "in the zone" or "in flow" was first scientifically described by psychologist Mihaly Csikszentmihalyi in his 1990 book "Flow." He found that the optimal experience occurs when challenge and skill are perfectly balanced — too easy and you\'re bored, too hard and you\'re anxious. Csikszentmihalyi interviewed thousands of people across cultures and found the same state described identically by chess grandmasters, surgeons, rock climbers, and factory workers: time distorts, self-consciousness vanishes, and the activity becomes effortless.',
    trivia_pt:'O fenômeno psicológico de estar "na zona" ou "em fluxo" foi descrito cientificamente pela primeira vez pelo psicólogo Mihaly Csikszentmihalyi em seu livro "Flow" de 1990. Ele descobriu que a experiência ótima ocorre quando desafio e habilidade estão perfeitamente equilibrados. Csikszentmihalyi entrevistou milhares de pessoas e encontrou o mesmo estado descrito identicamente por grandes mestres de xadrez, cirurgiões, alpinistas e operários de fábrica: o tempo se distorce, a autoconsciência desaparece e a atividade se torna sem esforço.',
    needed:null,
    special:'streak_50'
  },
  {
    id:'time_lord',
    icon:'⏳',
    name:'Time Lord',
    name_pt:'Senhor do Tempo',
    desc:'Complete a full run placing every card in the deck (win by emptying the deck)',
    desc_pt:'Complete uma partida colocando todas as cartas do baralho (vença esvaziando o baralho)',
    hint:'Empty the entire deck in a single run without losing all your lives. Try Free Play mode (no lives) to maximize chances.',
    hint_pt:'Esvazie o baralho inteiro em uma única partida sem perder todas as suas vidas. Tente o modo Jogo Livre (sem vidas) para maximizar as chances.',
    trivia:'The concept of "deep time" — that the Earth is billions of years old — was one of the most psychologically destabilizing discoveries in human history. Before geologist James Hutton proposed it in 1788, virtually all cultures assumed human history was essentially all of history. Charles Darwin wrote that understanding deep time was essential to accepting evolution. Carl Sagan compressed cosmic history into a single calendar year: on that "Cosmic Calendar," all of recorded human history occupies just the final 10 seconds of December 31st.',
    trivia_pt:'O conceito de "tempo profundo" — que a Terra tem bilhões de anos — foi uma das descobertas psicologicamente mais desestabilizadoras da história humana. Antes do geólogo James Hutton propô-lo em 1788, praticamente todas as culturas assumiam que a história humana era essencialmente toda a história. Carl Sagan comprimiu a história cósmica em um único ano calendário: nesse "Calendário Cósmico," toda a história humana registrada ocupa apenas os últimos 10 segundos de 31 de dezembro.',
    needed:null,
    special:'full_deck'
  },
  {
    id:'daily_week',
    icon:'📝',
    name:'Creature of Habit',
    name_pt:'Criatura do Hábito',
    desc:'Complete the Daily Challenge 7 days in a row',
    desc_pt:'Complete o Desafio Diário por 7 dias seguidos',
    hint:'Play and finish the Daily Challenge every day for a full week without missing a day.',
    hint_pt:'Jogue e complete o Desafio Diário todos os dias durante uma semana inteira sem pular nenhum dia.',
    trivia:'Neurologists estimate it takes between 21 and 66 days to form a habit — not the popular myth of exactly 21 days, which traces back to a 1960 self-help book by plastic surgeon Maxwell Maltz, who noticed patients took "about 21 days" to adjust to their new appearance. The real figure comes from a 2010 University College London study tracking 96 people over 84 days. The average was 66 days, but ranged wildly from 18 to 254 days depending on the person and behavior. Simple habits form faster than complex ones. Fortunately, missing one day doesn\'t break the chain.',
    trivia_pt:'Neurologistas estimam que leva entre 21 e 66 dias para formar um hábito — não o mito popular de exatamente 21 dias, que remonta a um livro de autoajuda de 1960 do cirurgião plástico Maxwell Maltz, que notou que os pacientes levavam "cerca de 21 dias" para se ajustar à nova aparência. O número real vem de um estudo de 2010 da University College London acompanhando 96 pessoas por 84 dias. A média foi de 66 dias, mas variou enormemente de 18 a 254 dias. Felizmente, pular um dia não quebra a corrente.',
    needed:null,
    special:'daily_streak_7'
  },
  {
    id:'daily_forty',
    icon:'🗓️',
    name:'The Long Count',
    name_pt:'A Grande Contagem',
    desc:'Complete the Daily Challenge 40 days in a row',
    desc_pt:'Complete o Desafio Diário por 40 dias seguidos',
    hint:'Maintain an unbroken Daily Challenge streak for 40 consecutive days.',
    hint_pt:'Mantenha uma sequência ininterrupta de 40 dias no Desafio Diário.',
    trivia:'The Maya Long Count calendar — one of the most sophisticated timekeeping systems ever devised — tracked time in cycles of 400 years called b\'ak\'tuns, each containing 144,000 days. The calendar began on a mythological creation date equivalent to August 11, 3114 BCE, and its 13th b\'ak\'tun cycle famously ended on December 21, 2012 — which many misread as a doomsday prophecy. The Maya themselves left no such prediction. The Long Count could represent any date across roughly 63 million years, making it one of the longest-range calendar systems ever created by any civilization.',
    trivia_pt:'O calendário da Contagem Longa maia — um dos sistemas de registro de tempo mais sofisticados já criados — rastreava o tempo em ciclos de 400 anos chamados b\'ak\'tuns, cada um contendo 144.000 dias. O calendário começou em uma data de criação mitológica equivalente a 11 de agosto de 3114 a.C., e seu 13º ciclo b\'ak\'tun terminou em 21 de dezembro de 2012 — que muitos interpretaram erroneamente como uma profecia do fim do mundo. Os próprios maias não deixaram tal previsão. A Contagem Longa pode representar qualquer data ao longo de aproximadamente 63 milhões de anos.',
    needed:null,
    special:'daily_streak_40'
  },
];
